[platformio]
default_envs = seeed_xiao_esp32c3

[env]
platform = espressif32
framework = arduino
monitor_speed = 115200
lib_deps =
  jgromes/RadioLib @ 7.7.1
build_flags =
  -DCORE_DEBUG_LEVEL=1

[env:seeed_xiao_esp32c3]
board = seeed_xiao_esp32c3
build_src_filter =
  +<repeater_v3.cpp>
  -<repeater_v2.cpp>
  -<endpoint_messenger.cpp>
  -<endpoint_messenger_v2.cpp>
  -<main.cpp>

[env:adafruit_feather_esp32s2]
board = adafruit_feather_esp32s2
build_flags =
  ${env.build_flags}
  -DHOLDEN_TARGET_S2=1
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DARDUINO_USB_MODE=0
build_src_filter =
  +<repeater_v3.cpp>
  -<repeater_v2.cpp>
  -<endpoint_messenger.cpp>
  -<endpoint_messenger_v2.cpp>
  -<main.cpp>

[env:heltec_wifi_lora_32_V3]
board = heltec_wifi_lora_32_V3
build_flags =
  ${env.build_flags}
  -DHOLDEN_ENDPOINT_HELTEC=1
build_src_filter =
  +<endpoint_messenger_v2.cpp>
  -<endpoint_messenger.cpp>
  -<repeater_v3.cpp>
  -<repeater_v2.cpp>
  -<main.cpp>

[env:home_xiao_esp32c3]
board = seeed_xiao_esp32c3
build_flags =
  ${env.build_flags}
  -DHOLDEN_ENDPOINT_HOME=1
build_src_filter =
  +<endpoint_messenger_v2.cpp>
  -<endpoint_messenger.cpp>
  -<repeater_v3.cpp>
  -<repeater_v2.cpp>
  -<main.cpp>
