[platformio]
default_envs = seeed_xiao_esp32c3

[env]
platform = espressif32
framework = arduino
monitor_speed = 115200
lib_deps =
  jgromes/RadioLib @ 7.7.1
build_flags =
  -DCORE_DEBUG_LEVEL=1
build_src_filter =
  +<repeater_v2.cpp>
  -<main.cpp>

[env:seeed_xiao_esp32c3]
board = seeed_xiao_esp32c3

[env:adafruit_feather_esp32s2]
board = adafruit_feather_esp32s2
build_flags =
  ${env.build_flags}
  -DHOLDEN_TARGET_S2=1
